name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-docker-frontend
        run: sh ./scripts/deploy.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          VERSION: latest