name: deploy

on:
    push:
        branches:
            - main
permissions:
    contents: write
    pages: write

jobs:
    deploy-storybook:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install and Build
              run: |
                  npm install
                  npm run build-storybook

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  FOLDER: dist-storybook
                  BRANCH: gh-pages
                  CLEAN: true
