/* eslint global-require: 0 */
export const CARDS_LIST = [
    {
        title: 'Резюме',
        description: 'Краткое содержание вашей встречи с возможностью редактирования',
        image: require('./_assets/point1.png'),
        isWhite: true,
        width: 105.98,
        height: 117.86,
        left: 9,
        top: 30,
        index: 1,
        transform: 'rotate(-10deg)',
    },
    {
        title: 'Важные цитаты',
        description: 'Которые определяются автоматически искусственным интеллектом',
        image: require('./_assets/point2.png'),
        isWhite: false,
        width: 182.19,
        height: 91.26,
        left: 18,
        top: 18,
        index: 2,
        transform: 'rotate(0)',
    },
    {
        title: 'Ключевые слова',
        description: 'Чтобы легко искать нужную информацию',
        image: require('./_assets/point3.png'),
        isWhite: true,
        width: 81,
        height: 87,
        left: 36,
        top: 26,
        index: 3,
        transform: 'rotate(10deg)',
    },
    {
        title: 'Полный текст + видеозапись',
        description: 'Возвращайтесь в любой момент!',
        image: require('./_assets/point4.png'),
        isWhite: false,
        width: 115,
        height: 107,
        index: 4,
        left: 50,
        top: 17,
        transform: 'rotate(0)',
    },
    {
        title: 'Основная информация',
        description: 'AI-конспект вашей конференции',
        image: require('./_assets/point5.png'),
        isWhite: true,
        width: 101.68,
        height: 105.47,
        left: 63,
        top: 23,
        index: 5,
        transform: 'rotate(-25deg)',
    },
    {
        title: 'Zoom-чат',
        description: 'Вы можете посмотреть каждое сообщение, которое было написано в ходе встречи',
        image: require('./_assets/point6.png'),
        isWhite: false,
        width: 168.32,
        height: 59.56,
        index: 6,
        left: 26,
        top: 13,
        transform: 'rotate(20deg)',
    },
]
