export const CARDS_LIST = [
    {
        title: 'Резюме',
        description: 'Краткое содержание вашей встречи с возможностью редактирования',
        image: require('./_assets/point1.png'),
        isWhite: true,
        width: 105.98,
        height: 117.86,
        index: 0,
    },
    {
        title: 'Важные цитаты',
        description: 'Которые определяются автоматически искусственным интеллектом',
        image: require('./_assets/point2.png'),
        isWhite: false,
        width: 182.19,
        height: 91.26,
        index: 1,
    },
    {
        title: 'Ключевые слова',
        description: 'Чтобы легко искать нужную информацию',
        image: require('./_assets/point3.png'),
        isWhite: true,
        width: 81,
        height: 87,
        index: 2,
    },
    {
        title: 'Полный текст + видеозапись',
        description: 'Возвращайтесь в любой момент!',
        image: require('./_assets/point4.png'),
        isWhite: false,
        width: 115,
        height: 107,
        index: 3,
    },
    {
        title: 'Основная информация',
        description: 'AI-конспект вашей конференции',
        image: require('./_assets/point5.png'),
        isWhite: true,
        width: 101.68,
        height: 105.47,
        index: 4,
    },
    {
        title: 'Zoom-чат',
        description: 'Вы можете посмотреть каждое сообщение, которое было написано в ходе встречи',
        image: require('./_assets/point6.png'),
        isWhite: false,
        width: 168.32,
        height: 59.56,
        index: 5,
    },
]
